import type { Metadata } from "next";
import localFont from "next/font/local";
import CursorComponent from "./components/cursor/cursor.tsx";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CursorComponent />
        {children}
      </body>
    </html>
  );
}
